#!/bin/dash to_be_sourced
if test -z "$LINUXIFIED_REPO_DIRECTORY"; then
  echo "Error:"
  echo "It doesn't look like the test environment was initiallized!"
  false
else
  if test -f "$LINUXIFIED_REPO_DIRECTORY/test/gitwatch-bats-cleanup" \
    && cd "$LINUXIFIED_REPO_DIRECTORY/test/"
  then
    rm -I -rf "$LINUXIFIED_REPO_DIRECTORY/test/gitwatch-test-repo"
    docker_images=$(docker image ls -q gitwatch-lbats) > /dev/null
    for image in $docker_images; do
      docker image rm "$image"
    done
  else
    echo "Bad directory:"
    echo "expecting file '$LINUXIFIED_REPO_DIRECTORY/test/gitwatch-bats-cleanup' to exist"
    false
  fi
fi
